### ISSUE TITLE
Crashed while reporting in VSTS build

### ISSUE THREAD

**Issue by ur92** [sgbj/karma-tfs-reporter#2]
Hi, 
The reporter crashed while regular gulp test task over our build machine (hosted VSTS build server). 
Looks like the date failed to generate in order to create new report XML file before karma's tests run.
Any suggestions? 
```
2017-10-18T13:07:02.4210703Z [13:07:02] TypeError: Invalid date
2017-10-18T13:07:02.4210703Z     at TypeError (native)
2017-10-18T13:07:02.4210703Z     at d:\a\1\s\ExplorationEngine.Web\node_modules\karma-tfs-reporter\node_modules\dateformat\lib\dateformat.js:39:17
2017-10-18T13:07:02.4210703Z     at toISOString (d:\a\1\s\ExplorationEngine.Web\node_modules\karma-tfs-reporter\trx.js:14:12)
2017-10-18T13:07:02.4210703Z     at module.exports (d:\a\1\s\ExplorationEngine.Web\node_modules\karma-tfs-reporter\trx.js:119:24)
2017-10-18T13:07:02.4210703Z     at TfsReporter.onExit (d:\a\1\s\ExplorationEngine.Web\node_modules\karma-tfs-reporter\index.js:53:44)
2017-10-18T13:07:02.4220704Z     at Server.<anonymous> (d:\a\1\s\ExplorationEngine.Web\node_modules\karma\lib\events.js:13:22)
2017-10-18T13:07:02.4220704Z     at emitOne (events.js:101:20)
2017-10-18T13:07:02.4220704Z     at Server.emit (events.js:188:7)
2017-10-18T13:07:02.4220704Z     at Server.emitter.emit (d:\a\1\s\ExplorationEngine.Web\node_modules\karma-angular-filesort\lib\index.js:24:17)
2017-10-18T13:07:02.4220704Z     at Server.EventEmitter.emitAsync (d:\a\1\s\ExplorationEngine.Web\node_modules\karma\lib\events.js:72:10)
2017-10-18T13:07:02.4220704Z     at disconnectBrowsers (d:\a\1\s\ExplorationEngine.Web\node_modules\karma\lib\server.js:382:10)
2017-10-18T13:07:02.4220704Z     at Server.<anonymous> (d:\a\1\s\ExplorationEngine.Web\node_modules\karma\lib\server.js:337:7)
2017-10-18T13:07:02.4220704Z     at emitTwo (events.js:111:20)
2017-10-18T13:07:02.4220704Z     at Server.emit (events.js:191:7)
2017-10-18T13:07:02.4220704Z     at Server.emitter.emit (d:\a\1\s\ExplorationEngine.Web\node_modules\karma-angular-filesort\lib\index.js:24:17)
2017-10-18T13:07:02.4220704Z     at emitRunCompleteIfAllBrowsersDone (d:\a\1\s\ExplorationEngine.Web\node_modules\karma\lib\server.js:294:12)
```

**Comment by emtei** [comment]
@sgbj this is the same issue as #3 so it was fixed in #4 and can be closed :)
